作業目標<br>
熟悉陣列維度轉換，並且會擷取需要資料<br>
作業重點<br>
使用reshap須注意order用法<br>
where可以運用邏輯條件擷取資料

題目:<br>
1.將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")<br>
2.呈上題的array，找出被6除餘1的數的索引<br>

In [2]:
import numpy as np

In [3]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))
print('array1=',array1)
array2 = array1.reshape((5,6))
print('array2=',array2)

array1= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
array2= [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [6]:
#2.呈上題的array，找出被6除餘1的數的索引
arraymod = np.mod(array1, 6)
print('餘數=1 索引', np.where(arraymod == 1))

餘數=1 索引 (array([ 1,  7, 13, 19, 25], dtype=int64),)
